sudo: false
language: python
cache: pip

matrix:
    include:
      - python: 3.6
        env: TOX_ENV=py36
      - python: 3.7
        dist: xenial
        env: TOX_ENV=py37
      - python: 3.6
        env: TOX_ENV=lint

install:
  - pip install tox

script:
  - tox -e $TOX_ENV
